### ISSUE TITLE
Add clarification to Section 5.1.1.4. - CertProfile

### ISSUE THREAD

**Issue by HBrock** [lamps-wg/cmp-updates#28]
Liao Lijun adked the following question:

"As stated in " 2.4. New Section 5.1.1.3. - CertProfile":

   id-it-certProfile  OBJECT IDENTIFIER ::= {id-it 21}
   CertProfileValue ::= SEQUENCE SIZE (1..MAX) OF UTF8String

When used in an ir/cr/kur/genm, the value MUST NOT contain more elements than the number of CertReqMsg or InfoTypeAndValue elements and the certificate profile names refer to the elements in the given order.

My question is how to interpret the profile names if the names in the CertProfileValue field is less than the CertReqMsg? For example, there are 4 CertReqMsg entries, but only 3 values in CertProfileValue."

**Comment by HBrock** [comment]
I added this text to Section 5.1.1.4

"If you have multiple certReqMsg in an ir/cr/kur/p10cr, you MUST use the certProfile names in the same order as the certReqMsg. If you have no certProfile for one or several certReqMsg you can put theses either at the end of the sequence in the ir/cr/kur/p10cr or add an empty string as certProfile name to the sequence."

@johngray-dev @DDvO @xipki Do you have any comments?

**Comment by xipki** [comment]
Looks fine for me.

Lijun

Hendrik Brockhaus ***@***.***> schrieb am Mo., 22. Mai 2023,
17:45:

**Comment by johngray-dev** [comment]
The original text seemed clear to me, but I see where the question could come from, so I agree we should try to clarify without making it more complicated.  The updated message from David is good, I was going to suggest we make it clear that when CertProfile is required by one or more CertReqMsg, either the Cert profile Name or an empty string (to indicate no profile name), MUST be present in the same order.   So effectively we are saying they must have the same number of elements.  However, I think we still should allow a more efficient use case:

For example, say you have 3 certReqMsg (this is a common and supported use-case at Entrust).   Say you want to use a cert profile for only the 2nd certReqMsg.   The most efficient structure would be a Sequence of 2 CertProfiles (the first one being the empty string, the second one containing the profile name). Anything else should not be required.   The first one requires the empty String to act as a placeholder, but if all the ones at the end don't require it, then it shouldn't be needed.

In practise, the most efficient structure would be for the client to re-order the 3 certReqMsg so that the first one was the one that required the cert profile.   Then they would only need a CertProfileValue sequence of 1 as the 2nd and 3rd would both be empty.  Forcing them to send empty ASN.1 sequences is just a waste of bytes.

I can try to come up with some text to see if that can be further clarified if you agree that this type of efficiency makes sense.

**Comment by HBrock** [comment]
I think we are aligned on the issue. If you propose a leaner wording, it will be fine.

**Comment by HBrock** [comment]
Meeting 15.6.23
John will review and potentially add some text.

**Comment by johngray-dev** [comment]
I think this covers all the bases.  I also added clarity by specifically mentioned the names of the structures so it is clear what is being discussed.  

When used in a p10cr message, the CertProfileValue sequence MUST NOT contain multiple certificate profile names.  When used in an ir/cr/kur/genm message, the CertProfileValue sequence MUST NOT contain more certificate profile names than the number of CertReqMsg or GenMsgContent InfoTypeAndValue elements contained in the message body.

The certificate profile names in the CertProfileValue sequence relate to the CertReqMsg or GenMsgContent InfoTypeAndValue elements in the given order. An empty string means no certificate profile name is associated with the respective CertReqMsg or GenMsgContent InfoTypeAndValue element.  If the CertProfileValue sequence contains less certificate profile entries than CertReqMsg or GenMsgContent InfoTypeAndValue elements, the remaining CertReqMsg or GenMsgContent InfoTypeAndValue elements have no profile names associated with them.

**Comment by HBrock** [comment]
Thank you John. I will update the section accordingly.
